version: 2
updates:
  - package-ecosystem: nuget
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 20
  - package-ecosystem: "github-actions"
    directories:
      - "**/*"
    schedule:
      interval: daily
    open-pull-requests-limit: 20
    groups:
      aspire:
        patterns:
          - "*aspire*"
  - package-ecosystem: "npm"
    directories:
      - "**/*"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 20
    groups:
      storybook:
        patterns:
          - "*storybook*"
      eslint:
        patterns:
          - "*eslint*"
      quasar:
        patterns:
          - "*quasar*"
      vue:
        patterns:
          - "*vue*"
      tanstack:
        patterns:
          - "*tanstack*"
