version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/backend"
    schedule:
      interval: "weekly"
    groups:
      dotnet-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/ui/menu-website"
    schedule:
      interval: "weekly"
    groups:
      frontend-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
