version: 2
updates:
  - package-ecosystem: nuget
    directories:
      - "**/*"
    schedule:
      interval: daily
    open-pull-requests-limit: 20
  - package-ecosystem: "github-actions"
    directories:
      - "**/*"
    schedule:
      interval: daily
    open-pull-requests-limit: 20
  - package-ecosystem: "npm"
    directories:
      - "**/*"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 20
