# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: SonarCloudPrepare@1
  displayName: 'Prepare analysis on SonarCloud (PR)'
  inputs:
    SonarCloud: 'SonarCloud'
    organization: 'dgee2-github'
    scannerMode: 'MSBuild'
    projectKey: 'dgee2_Menu'
    projectName: 'Menu'
    extraProperties: |
      sonar.exclusions=**/obj/**,**/*.dll
  condition: eq(variables['Build.Reason'], 'PullRequest')
- task: SonarCloudPrepare@1
  displayName: 'Prepare analysis on SonarCloud'
  inputs:
    SonarCloud: 'SonarCloud'
    organization: 'dgee2-github'
    scannerMode: 'MSBuild'
    projectKey: 'dgee2_Menu'
    projectName: 'Menu'
    extraProperties: |
      sonar.exclusions=**/obj/**,**/*.dll
      sonar.branch.name=$(Build.SourceBranchName)
  condition: ne(variables['Build.Reason'], 'PullRequest')
- task: DotNetCoreCLI@2
  displayName: 'DotNet Restore'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'
    feedsToUse: 'select'
- task: DotNetCoreCLI@2
  displayName: 'DotNet Build'
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration) --no-restore --nologo'
    modifyOutputPath: true
- task: DotNetCoreCLI@2
  displayName: 'DotNet Test'
  inputs:
    command: 'test'
    projects: |
      **/*.test.csproj
      **/*.tests.csproj
    arguments: '--no-restore --no-build --configuration $(buildConfiguration) --nologo /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=./TestCoverage/'
    modifyOutputPath: true
- task: PublishCodeCoverageResults@1
  displayName: 'Publish Code Coverage Results'
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: '**/TestCoverage/coverage.cobertura.xml'
    failIfCoverageEmpty: true
- task: VSBuild@1
  inputs:
    solution: '**\*.sqlproj'
    configuration: '$(buildConfiguration)'
    clean: true
    maximumCpuCount: true
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Pipeline.Workspace)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  continueOnError: true
- task: SonarCloudAnalyze@1
  displayName: 'Run Code Analysis'
  continueOnError: false
- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'
  displayName: 'Publish Quality Gate Result'
  continueOnError: false