version: '3.4'

services:
  menuapi:
    image: ${DOCKER_REGISTRY-}menuapi
    hostname: menuapi
    build:
      context: ./MenuApi
      dockerfile: Dockerfile
    depends_on:
      - menudb
    ports:
      - 443
      - 80
    env_file: .env
  menudb:
    image: ${DOCKER_REGISTRY-}menudb
    hostname: menudb
    build:
      context: ./MenuDB
      dockerfile: Dockerfile
      args:
        - SQL_PASSWORD=${DOTNET_SQL_PASSWORD}
