version: '3.4'

services:
  menuapi:
    image: ${DOCKER_REGISTRY-}menuapi
    build:
      context: .
      dockerfile: MenuApi/Dockerfile
    depends_on:
      - menudb
  menudb:
    image: ${DOCKER_REGISTRY-}menudb
    build:
      context: ./MenuDB
      dockerfile: Dockerfile