// <auto-generated />
using MenuDB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MenuDB.Migrations
{
    [DbContext(typeof(MenuDbContext))]
    [Migration("20260307231933_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MenuDB.Data.IngredientEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Ingredient", (string)null);
                });

            modelBuilder.Entity("MenuDB.Data.IngredientUnitEntity", b =>
                {
                    b.Property<int>("IngredientId")
                        .HasColumnType("int");

                    b.Property<int>("UnitId")
                        .HasColumnType("int");

                    b.HasKey("IngredientId", "UnitId");

                    b.HasIndex("UnitId");

                    b.ToTable("IngredientUnit", (string)null);
                });

            modelBuilder.Entity("MenuDB.Data.RecipeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.HasKey("Id");

                    b.ToTable("Recipe", (string)null);
                });

            modelBuilder.Entity("MenuDB.Data.RecipeIngredientEntity", b =>
                {
                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.Property<int>("IngredientId")
                        .HasColumnType("int");

                    b.Property<int>("UnitId")
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,4)");

                    b.HasKey("RecipeId", "IngredientId", "UnitId");

                    b.HasIndex("IngredientId");

                    b.HasIndex("UnitId");

                    b.ToTable("RecipeIngredient", (string)null);
                });

            modelBuilder.Entity("MenuDB.Data.UnitEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Abbreviation")
                        .HasColumnType("varchar(5)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<int>("UnitTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UnitTypeId");

                    b.ToTable("Unit", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "ml",
                            Name = "Millilitres",
                            UnitTypeId = 1
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "l",
                            Name = "Litres",
                            UnitTypeId = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "Quantity",
                            UnitTypeId = 2
                        },
                        new
                        {
                            Id = 4,
                            Abbreviation = "g",
                            Name = "Grams",
                            UnitTypeId = 3
                        },
                        new
                        {
                            Id = 5,
                            Abbreviation = "kg",
                            Name = "Kilograms",
                            UnitTypeId = 3
                        });
                });

            modelBuilder.Entity("MenuDB.Data.UnitTypeEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("UnitType", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Volume"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Quantity"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Weight"
                        });
                });

            modelBuilder.Entity("MenuDB.Data.IngredientUnitEntity", b =>
                {
                    b.HasOne("MenuDB.Data.IngredientEntity", "Ingredient")
                        .WithMany("IngredientUnits")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_IngredientUnit_ToIngredient");

                    b.HasOne("MenuDB.Data.UnitEntity", "Unit")
                        .WithMany("IngredientUnits")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_IngredientUnit_ToUnit");

                    b.Navigation("Ingredient");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("MenuDB.Data.RecipeIngredientEntity", b =>
                {
                    b.HasOne("MenuDB.Data.IngredientEntity", "Ingredient")
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MenuDB.Data.RecipeEntity", "Recipe")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RecipeIngredient_ToRecipe");

                    b.HasOne("MenuDB.Data.UnitEntity", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Recipe");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("MenuDB.Data.UnitEntity", b =>
                {
                    b.HasOne("MenuDB.Data.UnitTypeEntity", "UnitType")
                        .WithMany("Units")
                        .HasForeignKey("UnitTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Unit_ToUnitType");

                    b.Navigation("UnitType");
                });

            modelBuilder.Entity("MenuDB.Data.IngredientEntity", b =>
                {
                    b.Navigation("IngredientUnits");
                });

            modelBuilder.Entity("MenuDB.Data.RecipeEntity", b =>
                {
                    b.Navigation("RecipeIngredients");
                });

            modelBuilder.Entity("MenuDB.Data.UnitEntity", b =>
                {
                    b.Navigation("IngredientUnits");
                });

            modelBuilder.Entity("MenuDB.Data.UnitTypeEntity", b =>
                {
                    b.Navigation("Units");
                });
#pragma warning restore 612, 618
        }
    }
}
