name: .NET Build
# For more information on this YAML file, please reference blog: https://agramont.net/blog/devops-intro-deploy-net-aspire-azure-github-actions

on:
  workflow_dispatch:
  push:
    # Run when commits are pushed to mainline branch (main or master)
    # Set this to the mainline branch you are using
    branches:
     - master
     - main
  pull_request:
    branches: [ "dev", "master", "main" ]

# Based from https://docs.github.com/en/actions/use-cases-and-examples/building-and-testing/building-and-testing-net
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup dotnet 9.x
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Install .NET Aspire workload
        run: dotnet workload install aspire

      - name: Install dependencies
        run: dotnet restore
        
      - name: Build
        run: dotnet build

      - name: clean ssl cert
        run: dotnet dev-certs https --clean

      - name: trust ssl cert
        run: dotnet dev-certs https --trust

      - name: Test with the dotnet CLI
        run: >
          dotnet test
          --configuration Release
          --logger "GitHubActions;summary.includeSkippedTests=true"
          -- RunConfiguration.CollectSourceInformation=true