name: Build
# For more information on this YAML file, please reference blog: https://agramont.net/blog/devops-intro-deploy-net-aspire-azure-github-actions

on:
  workflow_dispatch:
  push:
    # Run when commits are pushed to mainline branch (main or master)
    # Set this to the mainline branch you are using
    branches:
      - master
      - main
  pull_request:
    branches: ["dev", "master", "main"]

# Based from https://docs.github.com/en/actions/use-cases-and-examples/building-and-testing/building-and-testing-net
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Use Node.js 22.x
        uses: actions/setup-node@v6
        with:
          node-version: 22.x

      - name: Cache
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('ui/menu-website/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Enable pnpm with corepack
        run: corepack enable pnpm

      - name: Setup dotnet 9.x
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: "9.0.x"

      - name: Install .NET Aspire workload
        run: dotnet workload install aspire

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build

      - name: clean ssl cert
        run: dotnet dev-certs https --clean

      - name: trust ssl cert
        run: dotnet dev-certs https --trust

      - name: Test with the dotnet CLI
        run: >
          dotnet test
          --configuration Release
          --logger "GitHubActions;summary.includeSkippedTests=true"
          -- RunConfiguration.CollectSourceInformation=true
        env:
          parameters__Auth0TestClientId: ${{ vars.AUTH0_CLIENT_ID }}
          parameters__Auth0TestClientSecret: ${{ secrets.AUTH0_CLIENT_SECRET }}
          parameters__Auth0Domain: ${{ vars.AUTH0_DOMAIN }}
          parameters__Auth0Audience: http://localhost:65273

      - run: pnpm install --frozen-lockfile
        working-directory: ./ui/menu-website

      - run: pnpm run generate-openapi
        working-directory: ./ui/menu-website

      - run: pnpm run lint
        working-directory: ./ui/menu-website

      - run: pnpm run build
        working-directory: ./ui/menu-website

      - run: pnpm run test
        working-directory: ./ui/menu-website
